# Generated by Django 4.2.25 on 2025-11-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_and_answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
