# Generated by Django 4.2.25 on 2025-11-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_and_answers', '0003_rename_post_question_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_on']},
        ),
    ]
