# Generated by Django 4.2.25 on 2025-11-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_and_answers', '0004_alter_answer_options_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
